### ISSUE TITLE
Profile GitHub link is broken

### ISSUE THREAD

**Issue by ftnext** [MasonEgger/website#6]
When I clicked the GitHub link in your profile, I was redirected to a 404 page.

![profile_github](https://user-images.githubusercontent.com/21273221/108588035-6fa25700-739a-11eb-867a-53273f195a03.png)

![broken_github_link](https://user-images.githubusercontent.com/21273221/108587994-336ef680-739a-11eb-8b3e-5776f14efd85.png)

It seems the URL:https://github.com/Zelgius is broken.
https://github.com/MasonEgger/website/blob/0823e45ca1fd2998df780156e20ca2da03fee699/config.toml#L80

Changing it to https://github.com/MasonEgger seems to work.

FYI
Searched `https://github.com/Zelgius` in this repository, then found 1 link: https://github.com/Zelgius/Infrastructure-As-Code-Intro
https://github.com/MasonEgger/website/blob/0823e45ca1fd2998df780156e20ca2da03fee699/content/speaking/minimal-infra.md#L26
This link works fine, redirect to https://github.com/MasonEgger/Infrastructure-As-Code-Intro

P.S.
Your talk about context managers in ChiPy was great, thanks!

**Comment by MasonEgger** [comment]
Thanks for finding this!
